apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: kube-system
#type: Opaque
stringData:
  accessKeyID: YCredacted
  secretAccessKey: YCredacted
  endpoint: https://storage.yandexcloud.net
  region: ru-central1-d
